<?php

namespace App\Filament\Resources\Articles\Schemas;

use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Textarea;
use Filament\Schemas\Schema;

class ArticleForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                FileUpload::make('image')
                    ->image(),
                TextInput::make('type')
                    ->default(null),
                TextInput::make('path')
                    ->required(),
                TextInput::make('status')
                    ->required()
                    ->numeric()
                    ->default(1),
                TextInput::make('sort')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('title_en')
                    ->default(null),
                Textarea::make('description_en')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_en')
                    ->default(null),
                Textarea::make('meta_description_en')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_en')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_en')
                    ->default(null),
                TextInput::make('meta_h2_en')
                    ->default(null),
                TextInput::make('meta_h3_en')
                    ->default(null),
                TextInput::make('title_ru')
                    ->default(null),
                Textarea::make('description_ru')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_ru')
                    ->default(null),
                Textarea::make('meta_description_ru')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_ru')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_ru')
                    ->default(null),
                TextInput::make('meta_h2_ru')
                    ->default(null),
                TextInput::make('meta_h3_ru')
                    ->default(null),
                TextInput::make('title_de')
                    ->default(null),
                Textarea::make('description_de')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_de')
                    ->default(null),
                Textarea::make('meta_description_de')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_de')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_de')
                    ->default(null),
                TextInput::make('meta_h2_de')
                    ->default(null),
                TextInput::make('meta_h3_de')
                    ->default(null),
                TextInput::make('title_fr')
                    ->default(null),
                Textarea::make('description_fr')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_fr')
                    ->default(null),
                Textarea::make('meta_description_fr')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_fr')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_fr')
                    ->default(null),
                TextInput::make('meta_h2_fr')
                    ->default(null),
                TextInput::make('meta_h3_fr')
                    ->default(null),
                TextInput::make('title_it')
                    ->default(null),
                Textarea::make('description_it')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_it')
                    ->default(null),
                Textarea::make('meta_description_it')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_it')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_it')
                    ->default(null),
                TextInput::make('meta_h2_it')
                    ->default(null),
                TextInput::make('meta_h3_it')
                    ->default(null),
                TextInput::make('title_es')
                    ->default(null),
                Textarea::make('description_es')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_es')
                    ->default(null),
                Textarea::make('meta_description_es')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_es')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_es')
                    ->default(null),
                TextInput::make('meta_h2_es')
                    ->default(null),
                TextInput::make('meta_h3_es')
                    ->default(null),
                TextInput::make('title_uk')
                    ->default(null),
                Textarea::make('description_uk')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_title_uk')
                    ->default(null),
                Textarea::make('meta_description_uk')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('meta_keywords_uk')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('meta_h1_uk')
                    ->default(null),
                TextInput::make('meta_h2_uk')
                    ->default(null),
                TextInput::make('meta_h3_uk')
                    ->default(null),
            ]);
    }
}
