[program:rustresort-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/www-root/data/www/dev.rustresort.com/artisan queue:work --tries=3 --timeout=120 --sleep=3
autostart=true
autorestart=true
user=www-root
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/www-root/data/www/dev.rustresort.com/storage/logs/queue.log
stopwaitsecs=130
